### ISSUE TITLE
做了一些改进

### ISSUE THREAD

**Issue by rachpt** [Aruelius/cloud189#10]
![Snipaste_2020-05-18_22-52-59](https://user-images.githubusercontent.com/25758867/82227608-98ed0d00-995a-11ea-9fa2-954564aa9681.png)
https://i.loli.net/2020/05/18/xtWJVhlfGDgM7Se.png

新增交互功能，cookie 登录，等
还有一大堆坑需要填，目前 `login、clogin、ls、rm、share、down、upload`应该是正常的。

https://github.com/rachpt/cloud189

改动很大，考虑合并一下吗？

打包了一个 windows 平台的测试版本 https://lanzous.com/ics0cfc

**Comment by Aruelius** [comment]
看起来不错的样子，欢迎PR
