### ISSUE TITLE
不能下载带空格的文件

### ISSUE THREAD

**Issue by Aruelius** [Aruelius/cloud189#13]

**Comment by rachpt** [comment]
后面考虑使用 `'` `“` 以及 `\ `进行处理 文件名

试了下 通过 分享链接 好像很容易拿到下载链接

**Comment by Aruelius** [comment]
> 后面考虑使用 `'` `“` 以及 `\ `进行处理 文件名
> 
> 试了下 通过 分享链接 好像很容易拿到下载链接
> https://cloud.189.cn/v2/listShareDir.action?shareId=169172337&accessCode=i2wq&verifyCode=464435&orderBy=1&order=ASC&pageNum=1&pageSize=60
> 
> https://cloud.189.cn/v2/listShareDir.action?fileId=3142018771966969&shareId=169172337&accessCode=i2wq&orderBy=1&order=ASC&pageNum=1&pageSize=60

是的，并且不需要登录也行。

**Comment by rachpt** [comment]
比 蓝奏云 简单多了 🤣
