### ISSUE TITLE
签到，抽奖接口

### ISSUE THREAD

**Issue by cxyzzz** [Aruelius/cloud189#16]
直接发curl代码吧

每日签到：
`curl -s "http://api.cloud.189.cn//mkt/userSign.action" -H "SessionKey:arg1"`

抽奖1：
`curl -s -X GET -H "Host:m.cloud.189.cn" -H "User-Agent:xxxxx" -H "X-Requested-With:XMLHttpRequest" -H "Referer:https://m.cloud.189.cn/zhuanti/2016/sign/index.jsp?albumBackupOpened=0" -H "Cookie:COOKIE_LOGIN_USER=arg1" "https://m.cloud.189.cn/v2/drawPrizeMarketDetails.action?taskId=TASK_SIGNIN&activityId=ACT_SIGNIN&noCache=0.00729305869354957"`

抽奖2：
`curl -X GET -H "Host:m.cloud.189.cn" -H "User-Agent:xxxx" -H "X-Requested-With:XMLHttpRequest" -H "Referer:https://m.cloud.189.cn/zhuanti/2016/sign/index.jsp?albumBackupOpened=1" -H "Cookie:COOKIE_LOGIN_USER=arg1" "https://m.cloud.189.cn/v2/drawPrizeMarketDetails.action?taskId=TASK_SIGNIN_PHOTOS&activityId=ACT_SIGNIN&noCache=0.3608158782387296"`

**Comment by Aruelius** [comment]
get
