### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by PS0123456** [Aruelius/cloud189#18]
服务器linux挂载了一块同一公司的网络硬盘（上传的文件都在这硬盘上）。服务器本身速度渣，大约U AND D都是5M/S左右。

今天第一次使用贵工具上传一个文件夹，里面包含一个22G的大文件，upload之后，下行激增到50M/s，上行500kb/s左右，感觉很奇怪，jobs -f查看，running,进度始终为0，CT云上已经显示几KB的文件已完成。大约过了5-10分钟左右，发现finished，进度依然为0，CT云上显示22G的文件居然已经上传成功！！！！！！Suprised(甚至准备直接续费了~~~手动滑稽)！因为服务器上传速度一直显示400-500kb/s，而下行持续50M/s。无法理解~

前面跟帖咨询过后，再次上传一个类似大小22G的文件，服务器速度与前面类似，即下行短暂5-10分钟持续50M/S速度之后下降至100kb/s，上行一直400-500kb/s，但反复刷新CT云，发现并没有像第一次那样成功上传，进入jobs，发现进度很缓慢，进度条0.1%的非常缓慢递增....

Q1:第一次如此快的速度完成上传如何解释？
Q2：为什么会出现短暂5-10分钟持续50M/S下行速度而上行一直无速度？从文件大小、下行速度推算，下载（上传）完一个约22G文件就是只需要5-10分钟。挂载硬盘直连CT云了？但理论解释不通
Q3：根据以上推论，我第二次开始我的账号就被国区限速了？

PS：目前上传进度非常缓慢。。。。。上下行一直100-200！

**Comment by PS0123456** [comment]
经历实在很怪异，故文字很多，希望见谅。

**Comment by Aruelius** [comment]
1. 你们公司的带宽是多大
2. 你是使用什么命令查看网络流量的
3. 该文件你们公司特有的，还是网上都能下载的

**Comment by PS0123456** [comment]
> 1. 你们公司的带宽是多大
> 2. 你是使用什么命令查看网络流量的
> 3. 该文件你们公司特有的，还是网上都能下载的

1、辣鸡云上服务器，非公司，上下行都是50Mbps
2、nload
3、文件我搜索了一下公网种子服务器，没有，我理解你的猜测，的确不排除有人前面上传过。
但问题是为什么每次上传，都是先下行疯狂跑到400-500mbps之后就尿崩，上传一直没速度？

**Comment by PS0123456** [comment]
![2020-5-27 23-53-36](https://user-images.githubusercontent.com/13433663/83043346-566fb280-a075-11ea-8251-a3de10c3a73d.png)
这是我利用odupload上传至od的截图，这就是满速的，下行速度是因为硬盘需要先到服务器

**Comment by PS0123456** [comment]
![2020-5-28 0-1-53](https://user-images.githubusercontent.com/13433663/83044345-a1d69080-a076-11ea-8104-082ab915728b.png)
这是刚刚抓取的上传CT云~~~
持续时间大约就是文件大小除以速度~~

**Comment by rachpt** [comment]
可能是文件上传的块比较小的问题，再加上后回调显示进度，导致 io 开销大，还需要优化一下。
https://github.com/Aruelius/cloud189/blob/3dae3b0c3f33a0afde93ad956a2272b800de574f/cloud189/api/core.py#L402

**Comment by PS0123456** [comment]
> 可能是文件上传的块比较小的问题，再加上后面回调显示进度，导致 io 开销大，还需要优化一下。
> https://github.com/Aruelius/cloud189/blob/3dae3b0c3f33a0afde93ad956a2272b800de574f/cloud189/api/core.py#L402

挂了一夜没管，刚刚去看发现文件没有，上服务器一看：

> return self._sslobj.write(data)

> ConnectionResetError:` [Errno 104] Connection reset by peer

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):File "/usr/local/python3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
  File "/home/demo/cloud189/cloud189/cli/downloader.py", line 233, in run
    infos = self._disk.upload_dir(self._up_path, self._folder_id, callback=self._show_progress)
  File "/home/demo/cloud189/cloud189/api/core.py", line 577, in upload_dir
    res = self.upload_file(upload_file[0], upload_file[1], callback)
  File "/home/demo/cloud189/cloud189/api/core.py", line 537, in upload_file
    return self.upload_file_by_client(file_path, folder_id, callback)
  File "/home/demo/cloud189/cloud189/api/core.py", line 462, in upload_file_by_client
    code = self._upload_file_data(file_upload_url, upload_file_id, file_path, callback)
  File "/home/demo/cloud189/cloud189/api/core.py", line 405, in _upload_file_data
    resp = requests.put(url, data=data, headers=headers)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/api.py", line 134, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: [Errno 104] Connection reset by peer

大佬分析的很对，我看OneDriveUploader的Set block size. [Unit: M; 5<=b<=60;] (default "10")。

**Comment by rachpt** [comment]
验证没问题就 push 上来。
![Screenshot_20200528_161654](https://user-images.githubusercontent.com/25758867/83116926-0806f600-a0ff-11ea-889c-5528cb19297a.png)
![Screenshot_20200528_161640](https://user-images.githubusercontent.com/25758867/83116979-16eda880-a0ff-11ea-8a7d-ed00b5eae353.png)

**Comment by PS0123456** [comment]
> 验证没问题就 push 上来。
> ![Screenshot_20200528_161654](https://user-images.githubusercontent.com/25758867/83116926-0806f600-a0ff-11ea-889c-5528cb19297a.png)
> ![Screenshot_20200528_161640](https://user-images.githubusercontent.com/25758867/83116979-16eda880-a0ff-11ea-8a7d-ed00b5eae353.png)

期待，另外，大佬，咱一个圈子的啊~~~

**Comment by rachpt** [comment]
> > 验证没问题就 push 上来。
> 
> 期待，另外，大佬，咱一个圈子的啊~~~

是一个圈 https://github.com/rachpt/AutoSeed 
![64006a47a40a198135a90d](https://user-images.githubusercontent.com/25758867/83120924-40f59980-a104-11ea-8907-52b520bb3717.jpg)

**Comment by PS0123456** [comment]
> > > 验证没问题就 push 上来。
> > 
> > 
> > 期待，另外，大佬，咱一个圈子的啊~~~
> 
> 是一个圈 https://github.com/rachpt/AutoSeed
> ![64006a47a40a198135a90d](https://user-images.githubusercontent.com/25758867/83120924-40f59980-a104-11ea-8907-52b520bb3717.jpg)

......大佬大佬，原来可以这么玩~~~失敬失敬！

**Comment by PS0123456** [comment]
再次打扰各位大佬，路径怎么都不对，文件夹

> Director\'s.Cut.720p.BluRay.DTS.x264-DON
还是PY需要引号？

**Comment by rachpt** [comment]
> 再次打扰各位大佬，路径怎么都不对，文件夹
> 
> > Director's.Cut.720p.BluRay.DTS.x264-DON
> > 还是PY需要引号？

`‘`、`“`、`\` 是特殊符号，使用 双引号包裹
https://github.com/Aruelius/cloud189/commit/7210c14c606f611832ffb543884ceae48ff4d62e

**Comment by PS0123456** [comment]
> > 再次打扰各位大佬，路径怎么都不对，文件夹
> > > Director's.Cut.720p.BluRay.DTS.x264-DON
> > > 还是PY需要引号？
> 
> `‘`、`“`、`\` 是特殊符号，使用 双引号包裹试试
> [7210c14](https://github.com/Aruelius/cloud189/commit/7210c14c606f611832ffb543884ceae48ff4d62e)

![2020-5-28 17-37-7](https://user-images.githubusercontent.com/13433663/83125388-0d1d7280-a10a-11ea-98cf-6c896d8337e7.png)
 git pull之后，没卵用啊~~~~~

**Comment by rachpt** [comment]
> > > 再次打扰各位大佬，路径怎么都不对，文件夹
> > > > Director's.Cut.720p.BluRay.DTS.x264-DON
> > > > 还是PY需要引号？
> > 
> > 
> > `‘`、`“`、`\` 是特殊符号，使用 双引号包裹试试
> > [7210c14](https://github.com/Aruelius/cloud189/commit/7210c14c606f611832ffb543884ceae48ff4d62e)
> 
> git pull之后，没卵用啊~~~~~

那可能就是你的盒子和 天翼云 的连接性比较差了

**Comment by PS0123456** [comment]
> > > > 再次打扰各位大佬，路径怎么都不对，文件夹
> > > > > Director's.Cut.720p.BluRay.DTS.x264-DON
> > > > > 还是PY需要引号？
> > > 
> > > 
> > > `‘`、`“`、`\` 是特殊符号，使用 双引号包裹试试
> > > [7210c14](https://github.com/Aruelius/cloud189/commit/7210c14c606f611832ffb543884ceae48ff4d62e)
> > 
> > 
> > git pull之后，没卵用啊~~~~~
> 
> 那可能就是你的盒子和 天翼云 的连接性比较差了

大佬能不能把我的下行降下来？这种状态不正常啊，我觉得不是我连接性差，是IO的问题，大佬看看https://github.com/Aruelius/cloud189/issues/18#issuecomment-634760507，OD完全没问题啊。我试试ping CT云贵州服务器看看

**Comment by PS0123456** [comment]
> > > > 再次打扰各位大佬，路径怎么都不对，文件夹
> > > > > Director's.Cut.720p.BluRay.DTS.x264-DON
> > > > > 还是PY需要引号？
> > > 
> > > 
> > > `‘`、`“`、`\` 是特殊符号，使用 双引号包裹试试
> > > [7210c14](https://github.com/Aruelius/cloud189/commit/7210c14c606f611832ffb543884ceae48ff4d62e)
> > 
> > 
> > git pull之后，没卵用啊~~~~~
> 
> 那可能就是你的盒子和 天翼云 的连接性比较差了

![2020-5-28 17-51-41](https://user-images.githubusercontent.com/13433663/83126827-f4ae5780-a10b-11ea-90b5-dc2c688bcaf1.png)
肯定不是连接性问题！！！！！！~~大佬再深入研究下？

**Comment by rachpt** [comment]
下载的话估计检测的是 盒子外面的总水管流量，没毛病
另外，这个延时是算特别大的了
可以试试看 OD 的连接性，肯定比这个好。

![Screenshot_20200528_190834](https://user-images.githubusercontent.com/25758867/83134445-f3365c80-a116-11ea-85a7-b565b80f17d9.png)

**Comment by PS0123456** [comment]
> 下载的话估计检测的是 盒子外面的总水管流量，没毛病
> 另外，这个延时是算特别大的了
> 可以试试看 OD 的连接性，肯定比这个好。
> 
> ![Screenshot_20200528_190834](https://user-images.githubusercontent.com/25758867/83134445-f3365c80-a116-11ea-85a7-b565b80f17d9.png)

那还是无法理解啊，为什么是下行疯狂拉，拉完文件大小，然后上行慢慢上传？我J实际硬盘大小又没增加。。。

**Comment by PS0123456** [comment]
大佬，再看看，我这边前面5点多上传的22G文件，还是报错：

> return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/demo/cloud189/cloud189/cli/downloader.py", line 233, in run
    infos = self._disk.upload_dir(self._up_path, self._folder_id, callback=self._show_progress)
  File "/home/demo/cloud189/cloud189/api/core.py", line 651, in upload_dir
    res = self.upload_file(upload_file[0], upload_file[1], callback)
  File "/home/demo/cloud189/cloud189/api/core.py", line 608, in upload_file
    return self.upload_file_by_client(file_path, folder_id, callback)
  File "/home/demo/cloud189/cloud189/api/core.py", line 529, in upload_file_by_client
    code = self._upload_file_data(
  File "/home/demo/cloud189/cloud189/api/core.py", line 468, in _upload_file_data
    resp = requests.put(url, data=post_data, headers=headers)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/api.py", line 134, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: [Errno 32] Broken pipe

**Comment by Aruelius** [comment]
上传好像一直是这样，大文件几乎都会报错，后续看看怎么优化，主要是他们天翼云盘单线程上传的，如果是多线程上传，就不存在这种事情了，后续我会看看改用客户端的 API，客户端上传是用 PUT 请求。
