### ISSUE TITLE
请增加签到 还有上传文件夹功能

### ISSUE THREAD

**Issue by jonntd** [Aruelius/cloud189#2]

**Comment by jonntd** [comment]
666

**Comment by Aruelius** [comment]
这个签到，是在哪里？

**Comment by jonntd** [comment]
> 这个签到，是在哪里？

在手机客户端 我的 -- 每日签到

**Comment by Aruelius** [comment]
上传文件夹写完了，https://github.com/Aruelius/cloud189/commit/d9521cbab6a5e81910aaafce5d3d75504cf874c7  签到我在手机上试过，每次 50MB，完全没什么用。。懒得抓包，如果有接口我可以直接写进去。
