### ISSUE TITLE
无限报错啊

### ISSUE THREAD

**Issue by DoubleShift** [Aruelius/cloud189#25]
登入自动退出，然后就再也不能运行了。

而且上个版本上传下载每次都报错，能上传就没管。
`
(py38) root@localhost:~/cloud189# python main.py
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    commander.login(("--auto", ))
  File "/root/cloud189/cloud189/cli/cli.py", line 98, in login
    self.refresh(config.work_id)
  File "/root/cloud189/cloud189/cli/config.py", line 221, in work_id
    return self._work_id
AttributeError: 'Config' object has no attribute '_work_id'
`

**Comment by rachpt** [comment]
看 更新说明啊啊啊
https://github.com/Aruelius/cloud189/commit/183e086773ed3f32c36697c0b5766991ce1219bc
**注意 `.config` 与以前版本不兼容** 需要删掉 `rm .config`，重新登录

**Comment by rachpt** [comment]
看 更新说明啊啊啊
https://github.com/Aruelius/cloud189/commit/183e086773ed3f32c36697c0b5766991ce1219bc
**注意 `.config` 与以前版本不兼容** ，需要删掉 `rm .config`，重新登录

**Comment by DoubleShift** [comment]
> 看 更新说明啊啊啊
> [183e086](https://github.com/Aruelius/cloud189/commit/183e086773ed3f32c36697c0b5766991ce1219bc)
> **注意 `.config` 与以前版本不兼容** ，需要删掉， `rm .config`，重新登录

找到原因了，rclone会创建1个.config文件夹，和你的.config冲突了。修改成.cloud189这种特殊的比较好。

**Comment by rachpt** [comment]
是 rclone 会在 cloud189 目录创建 `.config` 吗？
我对此表示不解，rclone 不会无故创建该文件吧。

如果是有协同作业，还请新开 issue 并提供更多的说明，(我对 rclone 不了解)
