### ISSUE TITLE
需要 铂金会员 和 普通会员 提供帮助

### ISSUE THREAD

**Issue by rachpt** [Aruelius/cloud189#27]
网页登录 铂金会员 和 普通会员账户，打开下面链接
https://cloud.189.cn/v2/getLoginedInfos.action?showPC=true
提供返回的 json 数据结构(删除、修改个人敏感信息)，特别是需要 `superVip`的值。
目前已有 黄金会员 的信息。

https://github.com/Aruelius/cloud189/blob/d454e02ee9e5c124268b3b62ebf8ce107e3dd372/cloud189/cli/cli.py#L517

**Comment by Aruelius** [comment]
开铂金的应该少，普通会员也几乎不会用天翼盘
![image](https://user-images.githubusercontent.com/25380989/83861910-c9eb8100-a753-11ea-80f0-23813c92a080.png)

**Comment by xytoki** [comment]
```
0    普通用户
99   家庭云黄金会员
100  黄金会员
199  家庭云铂金会员
200  铂金会员
```
以上数据为逆向安卓客户端得到。
