### ISSUE TITLE
签到报错

### ISSUE THREAD

**Issue by yaoxinghuo** [Aruelius/cloud189#33]
直接运行python ./main.py sign --auto 后：
`Traceback (most recent call last):
  File "/Users/Terry/it/source/git/cloud189/main.py", line 9, in <module>
    commander.login(("--auto", ))
  File "/Users/Terry/it/source/git/cloud189/cloud189/cli/cli.py", line 99, in login
    self.refresh(config.work_id)
  File "/Users/Terry/it/source/git/cloud189/cloud189/cli/cli.py", line 82, in refresh
    self._file_list, self._path_list = self._disk.get_file_list(dir_id)
  File "/Users/Terry/it/source/git/cloud189/cloud189/api/core.py", line 338, in get_file_list
    resp = resp.json()
`

把resp打印出来看后，看到这个url：https://cloud.189.cn/v2/listFiles.action 的resp是：

`<script>
var redirect_url = 'https://open.e.189.cn/api/account/unifyAccountLogout.do?appId=cloud&version=v1.5&clientType=10010&format=redirect&paras=CD0FACA0DDE015FE627653D28500E5E7D1D04CAE6B98D3C61D827AB5F71F859C17BF5104721155FB9FFDF782CD7C17E20486205229635AA92EE3F6024AAE02CCCCF092102B46447DCB5343FB1D7AE2A08C0E3D92DAF11B85D69251FF&sign=0C7A95FDAF81F219B1E5F437FCA0163C5958CB74';

if(redirect_url == 'null' || redirect_url == ''){
	redirect_url = '';
}
parent.window.document.location.href=redirect_url;
</script>
<div class="loading_gif" style="position:absolute;top:50%;left:0;width:100%;margin-top:-10px;text-align:center;">加载中...</div>`

**Comment by Aruelius** [comment]
应该是网络问题，重新执行一下，或者 `git pull` 更新一下代码，我这里执行是没有问题的。
![image](https://user-images.githubusercontent.com/25380989/84099452-3b6d4d00-aa3c-11ea-8935-eba290aaefbd.png)

**Comment by yaoxinghuo** [comment]
找到原因了，我是用户名密码登录后，执行了bye退出了，然后第二天执行了`python ./main.py sign --auto`后，估计是处于退出状态后，执行了签到，天翼服务器返回了跳转登录的resp，而不是标准的json，导致解析错误

**Comment by Aruelius** [comment]
应该是 Cookie 失效了。
