### ISSUE TITLE
作者我想亲你一口可以吗 请教怎么显示上传速度

### ISSUE THREAD

**Issue by helenpayne** [Aruelius/cloud189#37]
感谢作者提供这么好的项目，请问下怎么显示速度
/main.py upload -f /www/backup/site  -----F参数显示的是进度，没有速度，请问支持显示上传速度吗（KB/S）

**Comment by rachpt** [comment]
目前不支持显示速度，个人感觉没有实质上的意义，显示速度并不会使上传下载变快。

**Comment by helenpayne** [comment]
那请问支持指定上传的远端网盘路径吗 ，比如：upload -f /www/backup/database /网盘路径

**Comment by rachpt** [comment]
很遗憾，目前也是不支持上传文件时 指定上传至某个文件夹。
可以用两条指令组合实现类似的效果，(但需要注意 不能开多个进程进行不同处理)

```bash
/path/to/cloud189/main.sh cd /
/path/to/cloud189/main.sh cd www
/path/to/cloud189/main.sh cd backup
/path/to/cloud189/main.sh cd database
nohup /path/to/cloud189/main.sh upload  /www/backup/database &
# 注意 cd 一次只能跟子文件夹名或者 ..  /
```

之所以能这么做，是因为在 软件退出时会保存当前工作目录至 `.config` 文件，下次打开时自动切换进去。所以需要确保没有多个进程同时修改 `.config` 文件。

**Comment by helenpayne** [comment]
好的谢谢

**Comment by androiddisk** [comment]
> 很遗憾，目前也是不支持上传文件时 指定上传至某个文件夹。
> 可以用两条指令组合实现类似的效果，(但需要注意 不能开多个进程进行不同处理)
> 
> ```shell
> /path/to/cloud189/main.py cd /
> /path/to/cloud189/main.py cd www
> /path/to/cloud189/main.py cd backup
> /path/to/cloud189/main.py cd database
> nohup /path/to/cloud189/main.py upload  /www/backup/database &
> # 注意 cd 一次只能跟子文件夹名或者 ..  /
> # 单任务模式 **无需**自己添加 `-f` 参数
> ```
> 
> 之所以能这么做，是因为在 软件退出时会保存当前工作目录至 `.config` 文件，下次打开时自动切换进去。所以需要确保没有多个进程同时修改 `.config` 文件。

root@Lenovo:~/kooapk/kooapk-kitchen# /root/kooapk/kooapk-kitchen/tools/cloud189/main.py cd /
命令有误，或者不支持单任务运行 cd


cd 到根目录失败 请问是什么原因

**Comment by Aruelius** [comment]
`命令有误，或者不支持单任务运行 cd`
这就是原因
