### ISSUE TITLE
cli/cli.py 242行 SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by dominicx** [Aruelius/cloud189#40]
if not flag_arg_l:
                if file := self._file_list.find_by_name(fname):
                    if file.isFolder:
                        fid = file.id
                    else:
                        error(f"{fname} 非文件夹，显示当前目录文件")
                else:
                    error(f"{fname} 不存在，显示当前目录文件")

不知道哪里拼写异常。可是就是报错，pylint也显示这个。

**Comment by Aruelius** [comment]
Python 版本问题：本项目运行需要 Python3.8 及以上，这里有海象运算符。

**Comment by dominicx** [comment]
> Python 版本问题：本项目运行需要 Python3.8 及以上，这里有海象运算符。

谢谢！3.7.3，想办法升级去。

**Comment by Aruelius** [comment]
不客气
