### ISSUE TITLE
Pillow 安装失败

### ISSUE THREAD

**Issue by yirangeqian** [Aruelius/cloud189#45]
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ft66xc2b/pillow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ft66xc2b/pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3f_n35ve/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.8/Pillow Check the logs for full command output.

安装到最后一步提示这个，无法安装完成，求指教，设备是N1装了OPENWRT

**Comment by Aruelius** [comment]
参考 https://pillow-zh-cn.readthedocs.io/zh_CN/latest/installation.html

**Comment by rachpt** [comment]
如果没有遇到需要输入图片验证码，可以自己改一下这里
https://github.com/Aruelius/cloud189/blob/bf2e9509b93d6ce468261f9942f3440f71d18749/cloud189/cli/utils.py#L121
删掉 fabulous 的依赖。
这两个库的引入主要是 异地ip 特别是国外ip（vps） 登录用的。
