### ISSUE TITLE
国内云服务器上传速度很慢，文件1.1G左右

### ISSUE THREAD

**Issue by dawnli-github** [Aruelius/cloud189#56]
不知道是不是我自己的原因，已经关掉了代理。（阿里云的ecs学生机，深圳区域的）速度 90kb左右

**Comment by Aruelius** [comment]
你服务器自己上传就这么点速度吧，看这 90KB，那你服务器带宽（上传）肯定是 1Mbps 的。

**Comment by dawnli-github** [comment]
明白了！我还以为下载的时候那么快上传怎么那么慢的，谢谢啦！
