### ISSUE TITLE
Mac端的下载验证码有问题

### ISSUE THREAD

**Issue by izumiiAoba** [Aruelius/cloud189#57]
```bash
Error : [Errno 30] Read-only file system: '/captcha.png'
```
应该是没有权限向mac系统的`/`根目录写入图片，建议修改下写入的路径。

**Comment by Aruelius** [comment]
不是写根目录，而是写当前运行目录https://github.com/Aruelius/cloud189/blob/bf2e9509b93d6ce468261f9942f3440f71d18749/cloud189/cli/utils.py#L111

**Comment by izumiiAoba** [comment]
```bash
% python main.py 
Error : 文件夹 id=-11 无效(被删除), 将切换到根目录！
Error : 文件夹 id 无效 dir_id=-11, self._work_id=-11
正在检测更新...
(*/ω＼*) 暂无新版本发布~
但项目可能已经更新，建议去项目主页看看
如有 Bug 或建议,请提 Issue
Github: https://github.com/Aruelius/cloud189
> login
输入用户名:15623958611
输入密码:
Error : [Errno 30] Read-only file system: '/captcha.png'
```
会不会是和前面的这两行Error报错有关系？

**Comment by rachpt** [comment]
> 不是写根目录，而是写当前运行目录
> 
> https://github.com/Aruelius/cloud189/blob/bf2e9509b93d6ce468261f9942f3440f71d18749/cloud189/cli/utils.py#L111

这种写法不是很好，我更新一下
