### ISSUE TITLE
显示无效代码

### ISSUE THREAD

**Issue by Qa7060123** [Aruelius/cloud189#6]
ubuntu@ying:~/github/cloud189$ python ./189.py list
  File "./189.py", line 27
    def encrypt(password: str) -> str:
                        ^
SyntaxError: invalid syntax
咋整？？

**Comment by Aruelius** [comment]
升级 Python 版本，需要 Python3.6 及以上版本才能运行。

**Comment by Qa7060123** [comment]
OK了，必须root?

**Comment by Qa7060123** [comment]
能挂载？怎么搞，写在说明上撒

**Comment by Aruelius** [comment]
> OK了，必须root?

什么叫 `必须 root`

**Comment by Aruelius** [comment]
> 能挂载？怎么搞，写在说明上撒

还没写完

**Comment by Qa7060123** [comment]
问一下天翼云根目录ID怎么看

**Comment by Aruelius** [comment]
> 问一下天翼云根目录ID怎么看

根目录 ID 就是：`-11`
