### ISSUE TITLE
想知道签到hmacsha1加密内容

### ISSUE THREAD

**Issue by lksky8** [Aruelius/cloud189#62]
不是很懂py
只是想知道hmac加密的key是怎样获取
明文应该是：SessionKey=6601ff47-760e-4f9b-bca0-1a603399c2f7&Operate=GET&RequestURI=/mkt/userSign.action&Date=Wed, 14 Jul 2021 12:10:38 GMT

**Comment by Aruelius** [comment]
https://github.com/Aruelius/cloud189/blob/7a34bc781bfa840d1c1cdcb9c491693bd741f935/cloud189/api/token.py#L101

**Comment by lksky8** [comment]
> https://github.com/Aruelius/cloud189/blob/7a34bc781bfa840d1c1cdcb9c491693bd741f935/cloud189/api/token.py#L101

大致看懂了，加密的KEY=sessionKey？那sessionSecret这个是有什么作用

**Comment by lksky8** [comment]
已解决
