### ISSUE TITLE
请问怎么搭建ubuntu系统

### ISSUE THREAD

**Issue by qsect** [Aruelius/cloud189#71]
服务器是ubuntu系统，按照说明把sudo apt-get install libreadline-dev这条命令输入后，依赖安装了，然后再怎么操作呢？望详细说明，谢谢。

**Comment by Aruelius** [comment]
https://github.com/Aruelius/cloud189/blob/38a6eae1ef44e07ac3d25f1e6bdaf35c05301fe4/README.md?plain=1#L99
