### ISSUE TITLE
出现问题了求解def encrypt(password: str) -> str:                         ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by lrpli** [Aruelius/cloud189#8]
[root@server 189]# python 189.py list
  File "189.py", line 26
    def encrypt(password: str) -> str:
                        ^
SyntaxError: invalid syntax

大佬出现这个是什么操作  求解

python3.6  已经安装依赖

**Comment by Aruelius** [comment]
> [root@server 189]# python 189.py list
> File "189.py", line 26
> def encrypt(password: str) -> str:
> ^
> SyntaxError: invalid syntax
> 
> 大佬出现这个是什么操作 求解
> 
> python3.6 已经安装依赖

`python -V` 看看是不是 Python 3.6

**Comment by lrpli** [comment]
python -V 搞好了 显示3.6.4 
但是出现新问题了 如图 搞了一天了 都快崩溃了
![QQ截图20200430191848](https://user-images.githubusercontent.com/39980572/80704634-8465e380-8b17-11ea-8a72-ff4efbcffce8.png)

**Comment by Aruelius** [comment]
代码需要更新一下，可能是登录这里出了问题，你把 Cookie 文件删了，然后重新运行一下试试。

**Comment by lrpli** [comment]
> 代码需要更新一下，可能是登录这里出了问题，你把 Cookie 文件删了，然后重新运行一下试试。

压根就没有生成cookie文件啊。。。

**Comment by Aruelius** [comment]
经过测试，没发现有什么问题。
